### ISSUE TITLE
[Docs]  import tritonclient.http as httpclient deploy.sh  import tritonclient.http as httpclient

### ISSUE THREAD

**Issue by dlintw** [modularml/max#164]
### Where is the problem?

https://docs.modular.com/engine/get-started#2-run-your-first-model

### What can we do better?

After "run.sh", I tried to run "deploy.sh", get an error as:(I'm run docker inside WSL2 without NVIDA card)

ModuleNotFoundError: No module named 'tritonclient'

```
Digest: sha256:3eeb43884f94cdc830a4fc32baebbfe6e7300eced7670c5cf696823ea41e9e51
Status: Downloaded newer image for public.ecr.aws/modular/max-serving:latest
Compiling bert-mlm model.............
MAX Serving container started

Traceback (most recent call last):
  File "/home/dlin/prj/max/examples/inference/bert-python-torchscript/triton-inference.py", line 26, in <module>
    import tritonclient.http as httpclient
ModuleNotFoundError: No module named 'tritonclient'
dlin@DESKTOP-S5ITRU7 ~/p/m/e/i/bert-python-torchscript (main) [1]> python3 triton-inference.py --input "Paris is the [MASK] of France."
Traceback (most recent call last):
  File "/home/dlin/prj/max/examples/inference/bert-python-torchscript/triton-inference.py", line 26, in <module>
    import tritonclient.http as httpclient
ModuleNotFoundError: No module named 'tritonclient'
dlin@DESKTOP-S5ITRU7 ~/p/m/e/i/bert-python-torchscript (main) [1]> docker ps
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS          PORTS     NAMES
ee3dd93ca166   public.ecr.aws/modular/max-serving   "/opt/nvidia/nvidia_…"   11 minutes ago   Up 11 minutes             objective_galois
```

### Anything else?

I'm wonder, if the example can not work proper, does it proper to put issue here or other category?

**Comment by dlintw** [comment]
sorry, my mistake. it is already in requirement.txt
