### ISSUE TITLE
[BUG]: numpy version issue upon 2.0 release

### ISSUE THREAD

**Issue by mytechnotalent** [modularml/max#177]
### Bug description

```bash run.sh
+ INPUT_EXAMPLE='Paris is the [MASK] of France.'
+ MODEL_PATH=../../models/bert-mlm.torchscript
++ dirname run.sh
+ cd .
+ python3 ../common/bert-torchscript/download-model.py -o ../../models/bert-mlm.torchscript --mlm
 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
 
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
 
Traceback (most recent call last): File "/home/developer/test/max/examples/inference/bert-python-torchscript/../common/bert-torchscript/download-model.py", line 23, in
    import torch
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/__init__.py", line 1477, in
    from .functional import * # noqa: F403
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/functional.py", line 9, in
    import torch.nn.functional as F
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in
    from .modules import * # noqa: F403
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in
    device: torch.device = torch.device(torch._C._get_default_device()), # torch.device('cpu'),
/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()), # torch.device('cpu'),
Downloading model...
/home/developer/test/max-venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Saving model in TorchScript format...
'../../models/bert-mlm.torchscript' already exists.
 
+ python3 simple-inference.py --text 'Paris is the [MASK] of France.' --model-path ../../models/bert-mlm.torchscript
 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
 
If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
 
Traceback (most recent call last): File "/home/developer/test/max/examples/inference/bert-python-torchscript/simple-inference.py", line 19, in
    import torch
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/__init__.py", line 1477, in
    from .functional import * # noqa: F403
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/functional.py", line 9, in
    import torch.nn.functional as F
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/__init__.py", line 1, in
    from .modules import * # noqa: F403
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/modules/__init__.py", line 35, in
    from .transformer import TransformerEncoder, TransformerDecoder, \
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py", line 20, in
    device: torch.device = torch.device(torch._C._get_default_device()), # torch.device('cpu'),
/home/developer/test/max-venv/lib/python3.10/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()), # torch.device('cpu'),
Compiling model.
Done!
/home/developer/test/max-venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Processing input...
Input processed.
 
Traceback (most recent call last):
  File "/home/developer/test/max/examples/inference/bert-python-torchscript/simple-inference.py", line 100, in
    main()
  File "/home/developer/test/max/examples/inference/bert-python-torchscript/simple-inference.py", line 93, in main
    outputs = execute(args.model_path, args.text, input_dict)
  File "/home/developer/test/max/examples/inference/bert-python-torchscript/simple-inference.py", line 55, in execute
    outputs = model.execute(**inputs)["result0"]
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/max/engine/api.py", line 105, in execute
    kwargs[input_name] = np.array(input_value)
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/_tensor.py", line 1060, in __array__
    return handle_torch_function(Tensor.__array__, (self,), self, dtype=dtype)
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/overrides.py", line 1604, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
  File "/home/developer/test/max-venv/lib/python3.10/site-packages/torch/_tensor.py", line 1062, in __array__
    return self.numpy()
RuntimeError: Numpy is not available
 
### Steps to reproduce
 
https://docs.modular.com/max/get-started using WSL
 
SOLUTION: pip install numpy==1.23.1
 
 
### System information
 
```shell
- What OS did you do install MAX on WSL
- Provide version information for MAX by pasting the output of max -v `max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release`
```

**Comment by ehsanmok** [comment]
Thanks for reporting! this is a numpy 2.0 issue.

**Comment by ehsanmok** [comment]
Fixed in nightly. Will be in the next release.
