### ISSUE TITLE
[BUG]: Max Examples Tensorflow Roberta 

### ISSUE THREAD

**Issue by 1412kauti** [modularml/max#76]
### Bug description

I have tried to run the example run_tf.py with roberta and i end up with an error on a clean container, The error i got is as follows:

```
error: libdevice not found at ./libdevice.10.bc
Traceback (most recent call last):
  File "/home/ubuntu/max/examples/performance-showcase/run_tf.py", line 67, in <module>
    qps = common.run(lambda: loaded(inputs))
  File "/home/ubuntu/max/examples/performance-showcase/common.py", line 198, in run
    execute_cb()
  File "/home/ubuntu/max/examples/performance-showcase/run_tf.py", line 67, in <lambda>
    qps = common.run(lambda: loaded(inputs))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 816, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.UnknownError: Graph execution error:

Detected at node embeddings/LayerNorm/batchnorm/Rsqrt defined at (most recent call last):
<stack traces unavailable>
JIT compilation failed.
	 [[{{node embeddings/LayerNorm/batchnorm/Rsqrt}}]] [Op:__inference_restored_function_body_28682]
Exception ignored in: <function AtomicFunction.__del__ at 0x710ef31d0820>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/eager/polymorphic_function/atomic_function.py", line 291, in __del__
TypeError: 'NoneType' object is not subscriptable
```

### Steps to reproduce

```
python3 run_tf.py roberta 
```

### System information

- What OS did you do install MAX on ?
```
OS: Ubuntu 22.04.4 x86
CPU: AMD Ryzen 5 5600X 
GPU: NVIDIA GeForce RTX 3060 12GB
RAM: 32 GB DDR4 3600Mhz
```
- Provide version information for MAX by pasting the output of max -v`
```
max 24.1.0 (c176f84d)
Modular version 24.1.0-c176f84d-release
```
- Provide version information for Mojo by pasting the output of mojo -v`
```
mojo 24.1.0 (c176f84d)

```

- Provide Modular CLI version by pasting the output of `modular -v`
```
modular 0.5.1 (1b608e3d)
```

**Comment by sparadiso** [comment]
Thanks for filing this @1412kauti -- as a minor aside, this example is meant to be run through the driver `run.py` (this could be made clearer).

I suspect it will still fail with this error but curious what the experience is if you run `python3 run.py -m roberta`. 

Also, would you mind dropping the results of `pip freeze` here in the meantime? Thanks so much!

**Comment by Ivo-Balbaert** [comment]
I've got the same error with the Tensorflow part when running:  
`~/max/examples/performance-showcase$ python3 run.py -m roberta`

After the error output I also get:

Traceback (most recent call last):
```
  File "/home/ivo/max/examples/performance-showcase/run.py", line 67, in <module>
    f'Modular ({results["max"]:.2f} QPS) > TensorFlow ({results["tf"]:.2f} QPS). {next(exclamations)} It\'s {results["max"]/results["tf"]:.2f}x faster!'
KeyError: 'tf'
```

max 24.1.0 (c176f84d)
mojo 24.1.0 (c176f84d)
Modular version 24.1.0-c176f84d-release

My output of `pip freeze` is:

```
$ pip freeze
absl-py==2.1.0
aiohttp==3.9.3
aiosignal==1.3.1
ansiwrap==0.8.4
anyio==4.0.0
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.4.0
astunparse==1.6.3
async-lru==2.0.4
async-timeout==4.0.3
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.10.0
beniget==0.4.1
bleach==6.0.0
blinker==1.4
Brotli==1.0.9
cachetools==5.3.2
certifi==2023.7.22
cffi==1.15.1
chardet==4.0.0
charset-normalizer==3.2.0
click==8.1.7
comm==0.1.4
command-not-found==0.3
cryptography==3.4.8
cycler==0.11.0
dbus-python==1.2.18
debugpy==1.8.0
decorator==4.4.2
defusedxml==0.7.1
distro==1.7.0
distro-info==1.1+ubuntu0.1
entrypoints==0.4
exceptiongroup==1.1.3
executing==1.2.0
fastjsonschema==2.18.0
filelock==3.13.1
find-libpython==0.3.0
flatbuffers==23.5.26
fonttools==4.29.1
fqdn==1.5.1
frozenlist==1.4.1
fs==2.4.12
fsspec==2024.2.0
gast==0.5.4
gevent==24.2.1
geventhttpclient==2.0.2
google-auth==2.28.1
google-auth-oauthlib==1.2.0
google-pasta==0.2.0
greenlet==3.0.3
grpcio==1.60.1
h5py==3.10.0
html5lib==1.1
httplib2==0.20.2
huggingface-hub==0.20.3
idna==3.4
importlib-metadata==4.6.4
ipykernel==6.25.2
ipython==8.15.0
isoduration==20.11.0
jedi==0.19.0
jeepney==0.7.1
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.3
jupyter_server_terminals==0.4.4
jupyterlab==4.0.6
jupyterlab-pygments==0.2.2
jupyterlab_server==2.25.0
keras==2.15.0
keyring==23.5.0
kiwisolver==1.3.2
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
libclang==16.0.6
lxml==4.8.0
lz4==3.1.3+dfsg
Markdown==3.5.2
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.5.1
matplotlib-inline==0.1.6
max-engine==24.1.0
max-engine-libs==24.1.0
mdurl==0.1.2
mistune==3.0.1
ml-dtypes==0.2.0
more-itertools==8.10.0
mpmath==0.0.0
multidict==6.0.5
nbclient==0.8.0
nbconvert==7.8.0
nbformat==5.9.2
nest-asyncio==1.5.8
netifaces==0.11.0
networkx==3.2.1
notebook==7.0.4
notebook_shim==0.2.3
numpy==1.25.2
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.0
olefile==0.46
opt-einsum==3.3.0
overrides==7.4.0
packaging==21.3
pandocfilters==1.5.0
papermill==2.4.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
platformdirs==3.10.0
ply==3.11
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==4.25.3
psutil==5.9.5
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.5.1
pyasn1-modules==0.3.0
pycairo==1.20.1
pycparser==2.21
Pygments==2.16.1
PyGObject==3.42.1
PyJWT==2.3.0
pyparsing==2.4.7
python-apt==2.4.0+ubuntu2
python-dateutil==2.8.2
python-json-logger==2.0.7
python-rapidjson==1.14
pythran==0.10.0
pytz==2022.1
PyYAML==5.4.1
pyzmq==25.1.1
referencing==0.30.2
regex==2023.12.25
requests==2.31.0
requests-oauthlib==1.3.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.6.0
rpds-py==0.9.2
rsa==4.9
safetensors==0.4.2
scipy==1.8.0
SecretStorage==3.3.1
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.1
stack-data==0.6.2
sympy==1.9
systemd-python==234
tenacity==8.2.3
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow==2.15.0.post1
tensorflow-estimator==2.15.0
tensorflow-io-gcs-filesystem==0.36.0
termcolor==2.4.0
terminado==0.17.1
textwrap3==0.9.2
tinycss2==1.2.1
tokenizers==0.15.2
tomli==2.0.1
torch==2.2.0
tornado==6.3.3
tqdm==4.66.1
traitlets==5.9.0
transformers==4.38.0
triton==2.2.0
tritonclient==2.42.0
typing_extensions==4.8.0
ubuntu-advantage-tools==8001
ufoLib2==0.13.1
ufw==0.36.1
unattended-upgrades==0.1
unicodedata2==14.0.0
uri-template==1.3.0
urllib3==2.2.1
wadllib==1.3.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.3
Werkzeug==3.0.1
wrapt==1.14.1
yarl==1.9.4
zipp==1.0.0
zope.event==5.0
zope.interface==6.2
```

I run on WSL2, Ubuntu 22.04

mojo 24.1.0 (55ec12d6)

**Comment by 1412kauti** [comment]
the requirements.txt  in `examples/performance-showcase/requirements.txt` doesnt specify the specific versions, so when installing the environment, it pulls the latest release which for tensorflow would be 2.15.X (at this point), which seems to break the environment. But I did notice that it works perfectly fine with v2.13.0 which i found in `examples/inference/bert-c-tensorflow/requirements.txt`

**Comment by ValentineVGC** [comment]
@1412kauti can you check this and see if this is still an open issue?

Thank you!

**Comment by ValentineVGC** [comment]
@1412kauti I am going to close this for now, feel free to leave a comment if it persists
